### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by jlrasp** [gigibu5/OctoLight#11]
This is working great. Can I request the ability to control multiple led lights. I want to control two and would be cool if that could be added. Like you know either just add a second option for gpio pin.  Even if could be just controlled at the same time, or you could add a second button the GUI for the second light?    I’m new to octoprint so I don’t know if you can have multiple instances of the same plugin running?  Thanks for your plug-in and you consideration!

**Comment by gigibu5** [comment]
You can connect multiple lights to the same GPIO, but you would probably need some external circuitry. As for the multiple lights, that might come in a future release, but definitely not soon. You could install multiple installations, but the you would have to change the code, which is not permited by the AGPLv3 license used by Octoprint and my plugin.
