### ISSUE TITLE
OctoPrint's system menu

### ISSUE THREAD

**Issue by Thierry-Myron** [gigibu5/OctoLight#12]
For people using TouchUI or Mobile app, it would be great feature if the toggle was visible in the OctoPrint's system menu (config.yaml)
Cheers

**Comment by gigibu5** [comment]
Do you have any documentation or examples on how to do that?

**Comment by Thierry-Myron** [comment]
Hi, I have found Octolight Icon on ThouchUI, very small but working.
![image](https://user-images.githubusercontent.com/51226694/105651537-e0249800-5f02-11eb-816a-67a7631aeb36.png)

For the config on System Menu (Config.yaml) here is what I use:   
    -   action: lighton
        command: gpio -g write 17 1
        confirm: false
        name: Light ON
    -   action: light0ff
        command: gpio -g write 17 0
        confirm: false
        name: Light OFF

Would be great if you could integrate your API call in state of the gpio cmd.

**Comment by gigibu5** [comment]
You can make a pull request, but I do not have the time to intergrate it.
