### ISSUE TITLE
Remote activation and/or automated activation

### ISSUE THREAD

**Issue by mariowitdoek** [gigibu5/OctoLight#13]
**Is your feature request related to a problem? Please describe.**
Your plugin is just what I was developing (rather still in thinking phase): the pi that activates a GPIO for triggering a relay that put a 12V LED strip above the 3D printer ON/OFF.

**Describe the solution you'd like**
A possibility to switch the GPIO on/off from remote like a REST call or MQTT subscription. Then I can put the light on using home-assistant or NodeRed. Or via those utilities using the (tasmotised) light switch in my wall. 

**Describe alternatives you've considered**
Or just automatically when the printer is printing, but then again when you have a large print ... then the light is always on. 

**Additional context**
Great for the camera ...

**Comment by gigibu5** [comment]
You can turn on and off the light by just making a GET request to `hostname/api/plugins/octolight`. It will trigger the code.

**Comment by eloo** [comment]
For the record: 
its 
hostname/api/plugin/octolight
:+1:
