### ISSUE TITLE
Need some help with this relay

### ISSUE THREAD

**Issue by OxygenGS** [gigibu5/OctoLight#16]
![20210128_141359](https://user-images.githubusercontent.com/37304735/106144170-1fa5eb00-6174-11eb-9897-99b2a7c8f3ea.jpg)
I did buy this relay. How to connect this to my PSU of the printer and to the pin of the pi for switching it?

**Comment by derkaputte** [comment]
Hello, my understanding is that you "only" need to take 3 pins.

VCC - 5VDC (Pi)
GND - GND (Pi)
IN - Pin 13 (Pi, or which one you took)

SGND - is bridged to GND with the jumper, you can choose a seperate way to power up the 5VDC for the relay, but if you take the 5VDC from the Pi, you can use it without SGND.

Best regards and happy printing! ;)

**Comment by gigibu5** [comment]
That seems correct, but I think you need to connect VCC to 3.3V on the Pi

**Comment by OxygenGS** [comment]
Hmm ok. But i did order a 24v led stip. And it will be powerd by my meanwell PSU of the porinter. The PI gets power from its own source. Maybe this sounds dumb but.. can someone draw on my picture so i can see how to wire it??

**Comment by derkaputte** [comment]
![Relay_Pi](https://user-images.githubusercontent.com/22749670/106152583-e2465b00-617d-11eb-8e23-87b1f0f8d96f.jpg)

For more details, see " https://robotdyn.com/relay-module-1-relay-5v.html ".

BR Thomas

**Comment by OxygenGS** [comment]
Ty so so much :D

**Comment by gigibu5** [comment]
Can I close this issue?
