### ISSUE TITLE
Having two indipentend buttons for two light sources

### ISSUE THREAD

**Issue by kjoussen** [gigibu5/OctoLight#18]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by kjoussen** [comment]
I have two LED-Stripes and want to have them switched indipendently.
So two GPIOs and two relays but also two buttons.
Possible?

**Comment by gigibu5** [comment]
Duplicate of #11
