### ISSUE TITLE
Add the light control button to OctoScreen

### ISSUE THREAD

**Issue by syntos** [gigibu5/OctoLight#27]
I've installed the plugin and I can now control the light from the webinterface.

Because my printer is located in a seperate room I would like to be able to control the light from the OctoScreen plugin as well.

Is there an easy way to add a custom control to OctoScreen to use this plugin?

**Comment by gigibu5** [comment]
Probably not, I would have to check the OctoScreen plugin, but won't start even thinking about developing something like that until summer. Sorry :(
