### ISSUE TITLE
OctoEverwhere OctoApp

### ISSUE THREAD

**Issue by ProtomakerSprint** [gigibu5/OctoLight#39]
OctoEverywhere OctoApp Octolight plugin icon does not display

OctoPrint functions as expected dislpays the icon and Toggles LED on/off

_OctoEverywhere OctoApp say_:
If you use the website, you will be able to use all of your extensions on the desktop. However, if you use apps, like you're using above, only the plugins that the app developers support will work. I don't think that plugin is supported by OctoApp (which is what you're using), but if you reach out to the developer, he might be able to add it!

**Comment by gigibu5** [comment]
Sorry, but I am developing this plugin for the web interface only.
