### ISSUE TITLE
Sugesstion for readme update.

### ISSUE THREAD

**Issue by rickgartner** [gigibu5/OctoLight#8]
It might be worth mentioning the pins on the Raspberry are the actual pins and not the GPIO numbers.  I kept selecting 21 thinking is was the GPIO and it wouldn't work when I changed it to 40 it started working fine.  I'm using it to control a relay to turn on an LED strip.  Nice work!

**Comment by gigibu5** [comment]
This is clarified the README.md. Maybe I will add it in the settings menu.
